// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzmfzgaguasxusabzcxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6bWZ6Z2FndWFzeHVzYWJ6Y3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjU3NjIsImV4cCI6MjA2MjEwMTc2Mn0.-Jd1ZaRNdylnEYb20GR0wg9ccKaQiCi5cyMLPJ1xrZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);